# Example at: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - govet
    - gosec
    - ineffassign
    - misspell
    - staticcheck
    - unconvert

linters-settings:
  govet:
    enable-all: true

  misspell:
    locale: US
    ignore-words:
      - keymgmt
