# Example at: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - bodyclose
    - gocritic
    - misspell
    - unconvert
    - staticcheck
    - gosimple
    - stylecheck
    - goimports
    - depguard

linters-settings:
  govet:
    enable-all: true

  misspell:
    locale: US
    ignore-words:
      - keymgmt
      - cancelled
  stylecheck:
    checks: [ "all", "-ST1003" ]

issues:
  exclude:
    - ifElseChain
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
    - linters:
        - staticcheck
      text: "SA1019:"
